export const word = [
  'apple', 'television', 'parachute', 'car', 'Dorian', 'harmonica', 'guitar', 'mountain', 'cat', 'deer',
  'computer', 'bee', 'soccer', 'vacuum cleaner', 'billiards', 'tennis', 'skribbl', 'mario',
  'dog', 'elephant', 'giraffe', 'lion', 'penguin', 'snake', 'turtle', 'rabbit', 'monkey', 'shark',
  'whale', 'bear', 'duck', 'frog', 'owl', 'bat', 'spider', 'butterfly', 'snail', 'crab',
  'tree', 'flower', 'sun', 'moon', 'star', 'cloud', 'rain', 'volcano', 'island', 'beach',
  'chair', 'table', 'bed', 'lamp', 'clock', 'key', 'phone', 'door', 'window', 'mirror',
  'sofa', 'fridge', 'umbrella', 'scissors', 'pencil', 'book', 'glasses', 'camera', 'backpack', 'candle',
  'hammer', 'toothbrush', 'pillow', 'wallet', 'ring', 'crown', 'trash can', 'toilet', 'soap', 'towel',
  'banana', 'pizza', 'burger', 'ice cream', 'cake', 'cheese', 'cookie', 'donut', 'watermelon', 'carrot',
  'bread', 'egg', 'sandwich', 'french fries', 'sushi', 'popcorn', 'hot dog', 'strawberry', 'pineapple', 'chocolate',
  'coffee', 'milk', 'juice', 'teapot', 'lollipop',
  'bicycle', 'bus', 'airplane', 'boat', 'rocket', 'train', 'helicopter', 'submarine', 'truck', 'tractor',
  'motorcycle', 'scooter', 'ambulance', 'fire truck', 'taxi',
  'shirt', 'pants', 'shoe', 'hat', 'sock', 'jacket', 'dress', 'skirt', 'glove', 'scarf',
  'tie', 'belt', 'watch', 'boots', 'sunglasses',
  'house', 'castle', 'hospital', 'school', 'bridge', 'tent', 'church', 'statue', 'windmill', 'lighthouse',
  'basketball', 'baseball', 'golf', 'bowling', 'skate', 'snowboard', 'drum', 'piano', 'violin', 'trumpet',
  'kite', 'balloon', 'dice', 'cards', 'trophy',
  'alien', 'ghost', 'dragon', 'unicorn', 'robot', 'pirate', 'ninja', 'wizard', 'vampire', 'mummy',
  'astronaut', 'firefighter', 'doctor', 'chef', 'police', 'king', 'queen', 'mermaid', 'superhero', 'angel',
  'heart', 'skull', 'brain', 'eye', 'hand', 'foot', 'smile', 'moustache', 'bomb', 'coin',
  'chest', 'map', 'anchor', 'magnet', 'lightbulb', 'gift', 'flag', 'compass', 'feather', 'ladder'
];